### ISSUE TITLE
Completion is bugged

### ISSUE THREAD

**Issue by wvffle** [wvffle/mineflayer-dashboard#11]
So the completion is bugged now. At least in chat mode.

**Comment by GroobleDierne** [comment]
Did it stop working after a certain version?

**Comment by wvffle** [comment]
I don't know to be honest. Your PR hasn't changed anything regarding completion.

I've tried to complete a command and it tried to finish with player names that werent even starting with same letters, so... something is really broken.

Could be lacking some return or something

**Comment by GroobleDierne** [comment]
Ok I found a solution, I make the PR
