### ISSUE TITLE
Cannot access property "commands" of undefined

### ISSUE THREAD

**Issue by goldeneas** [wvffle/mineflayer-dashboard#16]
This happens even with the example that is in the main page.
I believe I have correctly loaded up the plugin but it still gives me this error.

**Comment by amoraschi** [comment]
They're 2 examples in one. Use the second one after the `//or`

**Comment by goldeneas** [comment]
I did, I've used the one after that line and I've only used one

**Comment by wvffle** [comment]
You can use those after the `spawn` or `login` event

**Comment by wvffle** [comment]
Take a look at https://github.com/wvffle/mineflayer-dashboard/blob/master/test/manual/test.mjs#L29

**Comment by goldeneas** [comment]
I've tried loading the plugin inside the spawn and login events, but it still tells me that dashboard is undefined. Do I have to send my code?

**Comment by wvffle** [comment]
You have to load it just after you define the `bot` variable. But you can use the `bot.dashboard` after `login` or spawn event:
```js
const bot = mineflayer.createBot(options)

bot.loadPlugin(dashboard)

bot.once('spawn', () => {
  bot.dashboard.commands.hello = () => {
    bot.dashboard.log('hello')
  }
})
```

If that doesn't help, send your code along with package.json

**Comment by goldeneas** [comment]
It works now, many thanks. It wasn't working due to me not registering the command inside of the spawn event.
