### ISSUE TITLE
Dashboard crashes

### ISSUE THREAD

**Issue by BlasterStudios** [wvffle/mineflayer-dashboard#17]
Every time I open the dashboard it immediately crashes and says:
(node:15840) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process].
I tried commenting my whole code and keep just the dashboard code and it still crashes.

**Comment by wvffle** [comment]
Do you mind sharing the actual code?

**Comment by BlasterStudios** [comment]
ok nvm I was using the plugin wrong.
