### ISSUE TITLE
bot.dashboard is undefined when version of the bot is undefined.

### ISSUE THREAD

**Issue by random-logic** [wvffle/mineflayer-dashboard#18]
If I was to create a bot with the version set to false, bot.dashboard is undefined. This would work fine if the version was set to a valid version instead of false. However, mineflayer allows the version to be set to false, which in this case the bot would automatically detect the correct version. Not a critical issue, but it would be a nice enhancement to have mineflayer-dashboard work when the version of the bot set to false. Thanks!

I am using mineflayer-dashboard 2.0.0 and mineflayer 3.0.0
```js
//Here is the code I am referring to

const HOST = 'localhost'
const PORT = 55565
const USERNAME = 'some username'
const PASSWORD = null
const VERSION = false // OK FOR MINEFLAYER, BUT DOES NOT WORK WITH MINEFLAYER-DASHBOARD
// WORKS IF VERSION = '1.16.4'

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: HOST,
  port: PORT,
  username: USERNAME,
  password: PASSWORD,
  version: VERSION
})

bot.loadPlugin(require('mineflayer-dashboard'))

global.console.log = bot.dashboard.log //bot.dashboard UNDEFINED BECAUSE VERSION = FALSE
global.console.error = bot.dashboard.log
```

**Comment by wvffle** [comment]
Have you tried waiting for `inject_allowed` event? 
```js
bot.once('inject_allowed', () => {
  bot.loadPlugin(require('mineflayer-dashboard'))

  global.console.log = bot.dashboard.log
  global.console.error = bot.dashboard.log
})
```

**Comment by random-logic** [comment]
It works now after I used the inject_allowed event. Unfortunately, it was not clearly documented as an event on the Mineflayer API. Thank you!
