### ISSUE TITLE
How to see all chat messages

### ISSUE THREAD

**Issue by ZoomGC** [wvffle/mineflayer-dashboard#28]
I am unable to see ALL chat messages in the server

**Comment by wvffle** [comment]
Can you show how the server chat looks like?
What kind of messages are ommited?

Any examples?

**Comment by ZoomGC** [comment]
It just does not show chat messages in any of the boxes, is there an option I must use to enable this functionality?

**Comment by wvffle** [comment]
You can try to add `chatPattern` option
- https://github.com/wvffle/mineflayer-dashboard#initialization

What's the version of mineflayer?

**Comment by Adeekonn** [comment]
Having the same issue I tried adding chatPattern option but its still the same!

**Comment by Adeekonn** [comment]
Here is a example of this!
![image](https://user-images.githubusercontent.com/100347327/155497967-4ac5d5b9-500a-4299-b639-7f67d1ae133a.png)

**Comment by Adeekonn** [comment]
It stays like that forever. ( note - there were people sending messages in the chat )

**Comment by ZoomGC** [comment]
This can be solved by logging the chat using the `bot.dashboard.log` function

Example:

```
bot.on('chat', (username, message) => {
  bot.dashboard.log(`${username} said "${message}"`)
```

**Comment by ZoomGC** [comment]
And if you are wanting to easily type messages (And it doesn't already do it with the :say command) then this is due to the say command using /forcesay, you can easily get around this by changing it from
 ```
bot.dashboard.commands['say'] = (user, ...words) => {
  const sentence = words.join(' ')
  bot.chat(`/forcesay ${username} ${sentence}`)
```
 (or something similar) to just:

```
bot.dashboard.commands['say'] = (user, ...words) => {
  const sentence = words.join(' ')
  bot.chat(`${sentence}`)
```

**Comment by Adeekonn** [comment]
still the main box doesn't show the chat msgs!
