### ISSUE TITLE
how to directly log to the mode window, or resize the log window.

### ISSUE THREAD

**Issue by 1tzkaos** [wvffle/mineflayer-dashboard#34]
title

**Comment by 1tzkaos** [comment]
To clarify, I am wondering if I can log to the mode window as I do with the log window. "bot.dashboard.log()" instead of making a mode, printing the line through the mode, etc. Also, I can't seem to be able to scroll in the windows.

**Comment by wvffle** [comment]
Hi @1tzkaos,

You ca use som lower level functions to print directly to the desired mode.
```js
const modeManager = require('mineflayer-dashboard/src/mode-manager')
modeManager.modes.chat.println('test')
```

About your scrolling issue: What terminal are you using? Does it support mouse input?

**Comment by 1tzkaos** [comment]
Thank you for replying so quickly @wvffle 

Windows Terminal. Windows build [Version 10.0.19045.1889]

I looked some stuff up and it may need to be 10.0.22xxx. I was trying to figure out how to have an image as the background of my terminal and that was the conclusion I found.

**Comment by wvffle** [comment]
I've never used Windows, nor Windows terminal. You could try https://github.com/alacritty/alacritty, which is an open source and cross platform terminal emulator. It should work just fine.

**Comment by 1tzkaos** [comment]
Ill check it out. Thank you very much

**Comment by 1tzkaos** [comment]
Ha! I feel really dumb. I thought Windows Terminal was the Windows default command prompt. I realized that it wasn't and that I had to download it from the Microsoft store. There I can change the background and have multiple terminals built into one.
