### ISSUE TITLE
Dashbord is broken

### ISSUE THREAD

**Issue by TheCaJlaT** [wvffle/mineflayer-dashboard#36]
What i do wrong?
![image](https://github.com/wvffle/mineflayer-dashboard/assets/66368050/3294c317-9325-41fc-b7ac-0dfe166a65e9)
![image](https://github.com/wvffle/mineflayer-dashboard/assets/66368050/ce8fa9a2-cdde-4c5b-8369-51c06f510246)

**Comment by wvffle** [comment]
Hi!

You have some dependency that is using `console.log` directly. You can hack this around by using the snippet provided in README: https://github.com/wvffle/mineflayer-dashboard#logging
