### ISSUE TITLE
What's the name for /msg messages?

### ISSUE THREAD

**Issue by Aglomation** [wvffle/mineflayer-dashboard#38]
edit: it seems like this kinda exists, but i want it to be able to see /msg messages (whispers) without needing a whisper mode. is this possible? i want to mix this with another mod so i can do /msg {account} tps and it sends back /r The tps is {tps}

**Comment by wvffle** [comment]
You can implement that with your custom mode like so:

```js
const myMode = new Mode({
   // your mode code...
   
   interpreter (message) {
     if (message.startsWith('/msg')) {
       return bot.chat(message)
     }
     
     // rest of your interpreter code...  
   }
})

bot.on('whisper', (username, message) => {
  whisper.println(`${username}: ${message}`)
})
```

But if you want your bot to respond with the TPS, you do not need to use the dashboard for that :) I'd suggest you to ask on mineflayer's discord for help with that as I haven't been maintaining the main repo for a couple of years now.

**Comment by wvffle** [comment]
@Muminwilmer I assume your issue is resolved. If not, please reopen it and give more input.

**Comment by Aglomation** [comment]
Wdym with "Your mode code" i'm really new to mineflayer lol, do you just mean the rest of my code??

**Comment by wvffle** [comment]
The `README` file in the repository has it's purpose, you know? ;)

Please read it first. There's a section that describes how to create custom modes for the dashboard.
