### ISSUE TITLE
borders are broken and input is shifted on windows 7

### ISSUE THREAD

**Issue by Florane** [wvffle/mineflayer-dashboard#8]
![image](https://user-images.githubusercontent.com/22117298/95600151-b7af8580-0a5a-11eb-8230-57b32aa5200b.png)

**Comment by wvffle** [comment]
You can try solution described in https://github.com/chjj/blessed/issues/41#issuecomment-695768850. It's actually a problem related to that library

**Comment by wvffle** [comment]
If you solve it, feel free to tell in the readme how to run it on windows. 

Closed, as it's not related to this lib.
